### PR TITLE
[Android] Allow redirections when protocol is changing

### PR DESCRIPTION
**Pull request by mathieudutour**
Android does not follow automatically the redirections when the protocol is changing (http -> https).

This PR fixes that.

### CODE REVIEW

**Comment by mathieudutour** [comment]
Any feedback?

**Comment by macdonst** [comment]
@mathieudutour sorry that we missed it. I've assigned it to myself to give you some feedback in the next couple of days.

**Comment by mnewmedia** [comment]
some days later :D

**Comment by macdonst** [comment]
Yeah, I looked into this a long time ago and forgot to comment on it. Java/Android specifically does not follow redirects from one protocol to another because of the security issues it may leave the user open to, see http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4620571 for more details.

**Pull request closed without merging**
